name: jui
description: A Flutter Ui component library, divided into four modules, general, data presentation, data entry, feedback, containing buttons, labels, text, headers, border containers, no_content placeholders and other components
version: 0.2.4
homepage: https://github.com/ThinkerJack/jui
repository: https://github.com/ThinkerJack/jui

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: